# -*- coding: utf-8 -*-
"""OCR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oIF5Lk7QkKiFmVE7Ch4pJRBJhgkFldVx
"""

pip install keras-ocr

import keras_ocr
import matplotlib.pyplot as plt

pipeline = keras_ocr.pipeline.Pipeline()

images = [
    keras_ocr.tools.read(img) for img in['/content/drive/MyDrive/image.png',
                         '/content/drive/MyDrive/image2.png']
]
len(images)

plt.figure(figsize = (10,20))
plt.imshow(images[0])

plt.figure(figsize = (10,20))
plt.imshow(images[1])

prediction_groups = pipeline.recognize(images)

fig, axs = plt.subplots(nrows=len(images), figsize=(10, 20))
for ax, image, predictions in zip(axs, images, prediction_groups):
    keras_ocr.tools.drawAnnotations(image=image, 
                                    predictions=predictions, 
                                    ax=ax)